spring:
  data:
    mongodb:
      uri: ${MONGODB_URL}
server:
  port: 8082
chen:
  base_path: /nebrija/qrnotify-topic
okta:
  oauth2:
    issuer: ${OKTA_DOMAIN}
    client-id: ${OKTA_CLIENT_ID}
    client-secret: ${OKTA_CLIENT_SECRET}
    scope: hao
